// Generated by gencpp from file natnet_msgs/MarkerList.msg
// DO NOT EDIT!


#ifndef NATNET_MSGS_MESSAGE_MARKERLIST_H
#define NATNET_MSGS_MESSAGE_MARKERLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>

namespace natnet_msgs
{
template <class ContainerAllocator>
struct MarkerList_
{
  typedef MarkerList_<ContainerAllocator> Type;

  MarkerList_()
    : header()
    , ids()
    , positions()  {
    }
  MarkerList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ids(_alloc)
    , positions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _ids_type;
  _ids_type ids;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Vector3_<ContainerAllocator> >::other >  _positions_type;
  _positions_type positions;





  typedef boost::shared_ptr< ::natnet_msgs::MarkerList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::natnet_msgs::MarkerList_<ContainerAllocator> const> ConstPtr;

}; // struct MarkerList_

typedef ::natnet_msgs::MarkerList_<std::allocator<void> > MarkerList;

typedef boost::shared_ptr< ::natnet_msgs::MarkerList > MarkerListPtr;
typedef boost::shared_ptr< ::natnet_msgs::MarkerList const> MarkerListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::natnet_msgs::MarkerList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::natnet_msgs::MarkerList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::natnet_msgs::MarkerList_<ContainerAllocator1> & lhs, const ::natnet_msgs::MarkerList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ids == rhs.ids &&
    lhs.positions == rhs.positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::natnet_msgs::MarkerList_<ContainerAllocator1> & lhs, const ::natnet_msgs::MarkerList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace natnet_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::natnet_msgs::MarkerList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::natnet_msgs::MarkerList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::natnet_msgs::MarkerList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::natnet_msgs::MarkerList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::natnet_msgs::MarkerList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::natnet_msgs::MarkerList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::natnet_msgs::MarkerList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acdfedb917425498ce6df7299be88b7c";
  }

  static const char* value(const ::natnet_msgs::MarkerList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacdfedb917425498ULL;
  static const uint64_t static_value2 = 0xce6df7299be88b7cULL;
};

template<class ContainerAllocator>
struct DataType< ::natnet_msgs::MarkerList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "natnet_msgs/MarkerList";
  }

  static const char* value(const ::natnet_msgs::MarkerList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::natnet_msgs::MarkerList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32[] ids\n"
"geometry_msgs/Vector3[] positions\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::natnet_msgs::MarkerList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::natnet_msgs::MarkerList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ids);
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MarkerList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::natnet_msgs::MarkerList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::natnet_msgs::MarkerList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.ids[i]);
    }
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NATNET_MSGS_MESSAGE_MARKERLIST_H
